### ISSUE TITLE
Firmware update unsuccessful

### ISSUE THREAD

**Issue by asinghx** [gudesystems/upload.py#10]
Due to disparity in naming convention, firmware update got skipped
![image](https://user-images.githubusercontent.com/108528505/231873409-cb1c1ced-de19-4c39-97ee-2160e2820e09.png)

**Comment by benbrummer** [comment]
https://files.gude-systems.com/fw/gude/firmware-epc8031-r2_v1.3.2-R2.bin
https://files.gude-systems.com/fw/gude/firmware-epc8031-r2_v1.3.2.bin

The wrong filename is caused by https://github.com/gudesystems/upload.py/blob/5560148caf77b845e881b42b4b06dcd59c8b9e98/gude/deployDev.py#L76

Older versions need to be downloaded without "-R2", too
https://files.gude-systems.com/fw/gude/firmware-epc8031-r2_v1.3.0.bin
https://files.gude-systems.com/fw/gude/firmware-epc8031-r2_v1.2.4.bin


Removing line 76-78 fixes this, but i guess there is/was a reason for checking for R2/r2

**Comment by fabian-n-gude-systems** [comment]
Thank you very much for your contribution. The issue should now be fixed. 
Please do not hesitate to contact us in case of any other issues.
